import bcrypt from "bcryptjs"

const data = {
  users: [
    {
      name: "John",
      email: "admin@example.com",
      password: bcrypt.hashSync("123456"),
      isAdmin: true,
    },
    {
      name: "Jane",
      email: "user@example.com",
      password: bcrypt.hashSync("123456"),
      isAdmin: false,
    },
  ],
  products: [
    {
      name: "Jacket",
      slug: "Jacket",
      category: "Shirt",
      image: "/images/shirt1.jpg",
      price: 170,
      brand: "Balenciaga",
      rating: 4.5,
      numReviews: 8,
      countInStock: 20,
      description: "A popular shirt",
    },
    {
      name: "Jacket",
      slug: "Jacket",
      category: "Shirt",
      image: "/images/shirt2.jpg",
      price: 580,
      brand: "Balenciaga",
      rating: 3.2,
      numReviews: 10,
      countInStock: 20,
      description: "A popular shirt",
    },
    {
      name: "Jacket",
      slug: "Jacket",
      category: "Shirt",
      image: "/images/shirt3.jpg",
      price: 990,
      brand: "Balenciaga",
      rating: 4.5,
      numReviews: 3,
      countInStock: 20,
      description: "A popular shirt",
    },
    {
      name: "Pants",
      slug: "Pants",
      category: "Pants",
      image: "/images/pants1.jpg",
      price: 900,
      brand: "Balenciaga",
      rating: 2.9,
      numReviews: 13,
      countInStock: 20,
      description: "Smart looking pants",
    },
    {
      name: "Pants",
      slug: "Pants",
      category: "Pants",
      image: "/images/pants2.jpg",
      price: 995,
      brand: "Balenciaga",
      rating: 3.5,
      numReviews: 7,
      countInStock: 20,
      description: "A popular pants",
    },
    {
      name: "Pants",
      slug: "Pants",
      category: "Pants",
      image: "/images/pants3.jpg",
      price: 800,
      brand: "Balenciaga",
      rating: 2.4,
      numReviews: 14,
      countInStock: 20,
      description: "A popular pants",
    },
  ],
}

export default data
